[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFilenames=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\ctooc\Desktop\mimo-island\cpp\build\MiMoIsland-Single.exe
FriendlyName=MiMo Island
AppLaunched=MiMoIsland.exe
PostInstallCmd=
FILE0="MiMoIsland.exe"
FILE1="Qt6Core.dll"
FILE2="Qt6Gui.dll"
FILE3="Qt6Widgets.dll"
FILE4="Qt6Network.dll"
FILE5="Qt6Svg.dll"
FILE6="qwindows.dll"
FILE7="qopensslbackend.dll"
FILE8="qschannelbackend.dll"
[SourceFiles]
SourceFiles0=C:\Users\ctooc\Desktop\mimo-island\cpp\build\Release
SourceFiles1=C:\Users\ctooc\Desktop\mimo-island\cpp\build\Release\platforms
SourceFiles2=C:\Users\ctooc\Desktop\mimo-island\cpp\build\Release\tls
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
%FILE3%=
%FILE4%=
%FILE5%=
[SourceFiles1]
%FILE6%=
[SourceFiles2]
%FILE7%=
%FILE8%=
